import Head from 'next/head';
import Image from 'next/image';
import formImage from "../public/form.png";
import { useFormik } from  "formik";
import * as Yup from "yup";
import { useRouter } from 'next/router';
import { motion as m } from 'framer-motion';

export default function Home() {
  //Router
  const router = useRouter();


  //Formik Logic
  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      country: 'Canada',
      terms: ''
    },
    // Validate Form
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, 'Name must be 20 characters or less')
        .required("Name is repuired"),
      email: Yup.string()
        .email('Invalid email address')
        .required("email is repuired."),
      terms: Yup.array()
        .required('Terms of service is must be checked')
    }),

    //Submit Form
    onSubmit: (values) => {
      console.log(values);
      router.push({pathname: '/success', query: values})
    }
  });

  // console.log(formik.errors);

  return (
    <m.div 
      initial={{opacity: 0}} 
      animate={{opacity: 1}}
      exit={{opacity: 0}}
      className="absolute w-full"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-screen items-center flex justify-center'>
        <form 
          onSubmit={formik.handleSubmit} 
          className='bg-white flex rounded-lg w-1/2 font-latoRegular'
        >
          {/* left side */}
          <div className='flex-1 text-gray-700 p-20'>

            <h1 className='text-3xl pb-2 font-latoBold'>Let&apos;s get started 👋</h1>
            <p className='text-lg text-gray-500'>Join our platform :)</p>

            <div className='mt-6'>
              {/* name input field */}
              <div className='pb-4'>
                <label 
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.name && formik.errors.name ? 'text-red-400' : ""
                  }`}
                  htmlFor="name"
                >
                  {formik.touched.name && formik.errors.name ? formik.errors.name : "Name"}
                </label>
                <input 
                  className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:outline-none'
                  type="text" 
                  name="name" 
                  placeholder='Enter your name' 
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>
              {/* Email input field */}
              <div className='pb-4'>
                <label 
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.email && formik.errors.email ? 'text-red-400' : ""
                  }`}
                  htmlFor="email"
                >
                  {formik.touched.email && formik.errors.email ? formik.errors.email : "Email"}
                </label>
                <input 
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:outline-none"
                  type="email" 
                  name="email" 
                  placeholder='Enter your email' 
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>
              {/* Country input field */}
              <div className='pb-4'>
                <label 
                  className="block font-latoBold text-sm pb-2" 
                  htmlFor="country"
                >
                  Country
                </label>
                <select 
                  name="country"
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:outline-none"
                  value={formik.values.country}
                  onChange={formik.handleChange}
                >
                  <option>Canada</option>
                  <option>United States</option>
                  <option>Japan</option>
                  <option>United Kingdom</option>
                </select>
              </div>
              {/* Terms of service */}
              <div className='pb-4'>
                <label 
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.terms && formik.errors.terms ? 'text-red-400' : ""
                  }`}
                  htmlFor="terms"
                >
                  {formik.touched.terms && formik.errors.terms ? formik.errors.terms : "Terms of service"}
                </label>
                <div className='flex items-center gap-2'>
                  <input 
                    className='h-5 w-5 border-4 border-gray-500 text-teal-500' 
                    type="checkbox" 
                    name="terms" 
                    value="checked"
                    onChange={formik.handleChange}
                  />
                  <p className='text-sm font-latoBold text-gray-500'>I agree the terms and service that my data will be taken and sold.</p>
                </div>
                
              </div>

              <button 
              type="submit"
              className="bg-teal-500 font-latoBold text-sm w-full text-white py-3 mt-6 rounded-md"
              >
                Start
              </button>
            </div>

          </div>

          {/* right side */}
          <div className='relative flex-1'>
            <Image 
              src={formImage} 
              alt="form-image" 
              fill 
              priority
              className='object-cover'
            />
          </div>
        </form>
      </main>
    </m.div>
  )
}
